dart-lang/source_span

CHANGELOG.md, lib/src/file.dart, pubspec.yaml
This behavior runs contrary to the rest of Dart's string handling, and
in particular breaks string_scanner. See dart-lang/string_scanner#4.
=> Deprecate the use of runes in SourceFile.

.travis.yml, lib/src/colors.dart, lib/src/file.dart, lib/src/location.dart, lib/src/location_mixin.dart, lib/src/span_mixin.dart, lib/src/span_with_context.dart, test/file_test.dart, test/highlight_test.dart, test/location_test.dart, test/span_test.dart
Fixes https://github.com/dart-lang/source_span/issues/18
=> Enable Travis-CI

lib/src/span.dart
The abstract `SourceSpan` class uses uninitialized final fields to put getters into the interface. This is invalid Dart 2 and blocks https://github.com/dart-lang/sdk/issues/33022
=> Avoid uninitialized final fields.

lib/src/span.dart
Typo is s/ANSII/ANSI/ and I found the doc insufficient in describing what format the ANSI code should be supplied in.
=> Fix typo and add example to message() and highlight()

CHANGELOG.md, lib/src/colors.dart, lib/src/highlighter.dart, lib/src/span.dart, lib/src/span_mixin.dart, lib/src/utils.dart, pubspec.yaml, test/highlight_test.dart, test/span_test.dart, test/utils_test.dart
* Fully highlights multiline spans.
* Includes line numbers.
* Uses Unicode glyphs for highlighting when available.
* Includes context after the last line of the span for a manually-constructed SourceSpanWithContext.
This draws heavy inspiration from Rust's multiline error highlighting.
---
This is what it looks like for a span that covers multiple full lines:
And for a span that covers multiple lines but only partially covers the first and last lines:
=> Improve span highlighting

CHANGELOG.md, lib/src/file.dart, pubspec.yaml, test/file_test.dart
According to the documentation, calling `SourceFile.span(start, [end])` without an explicit end offset should create a span that extends to the end of the file:
> If [end] isn't passed, it defaults to the end of the file.
Currently, the implementation returns a span with an end offset of `length - 1`, but because the end offset is always exclusive, this actually excludes the last character in the file. There wasn't an existing test for this case – the closest was one for `getText()` which correctly handles an omitted end offset.
In other words, I would expect the following to be true:
```dart
file.span(10).text == file.getText(10);
```
but they are not; the LHS here would be missing the last character.
---
This PR adjusts the `span()` implementation to return `length` instead of `length - …
=> SourceFile.span() should include last char when end offset omitted

CHANGELOG.md, lib/src/file.dart, lib/src/highlighter.dart, pubspec.yaml, test/file_test.dart, test/highlight_test.dart
This broke point spans at the beginning of lines elsewhere in the
file. Unfortunately, there's no way to disambiguate these currently.
SourceSpanWithContext doesn't have any information about where the
span appears in the context, so for point spans at column 0, it could
be at the beginning of the line or after the trailing newline.
We should eventually add something like
SourceSpanWithContext.indexInContext, but that'll require a breaking
release, since downstream users implement FileSpan as an interface.
=> Drop special support for point spans at the end of files

CHANGELOG.md, lib/src/highlighter.dart, pubspec.yaml, test/highlight_test.dart
If a span covered a trailing newline and a single additional line, it
went down a code path that resulted in a range error. That code path
has now been fixed.
Closes #32
=> Fix a highlighting bug

lib/src/file.dart
Fixes https://github.com/dart-lang/source_span/issues/37
=> Be more efficient with String.fromCharCodes

lib/src/file.dart
This reverts commit a5f8eadfe16c9479eea2f5328216ab2bb5f21e25.
This caused an unknown issue in rare cases with the test package.
=> Revert "Be more efficient with String.fromCharCodes (#44)"

analysis_options.yaml, lib/src/highlighter.dart, lib/src/span.dart
Change the markdown link style in a few places to work around a bug with
the analyzer where links that are split across lines are not recognized
correctly.
=> Enable comment_references lint

.travis.yml, CHANGELOG.md, analysis_options.yaml, lib/src/highlighter.dart, lib/src/span.dart, lib/src/span_exception.dart, lib/src/utils.dart, pubspec.yaml, test/highlight_test.dart, test/multiple_highlight_test.dart, test/span_test.dart
This makes it possible for applications to provide additional context
in their span-based messages. Like the existing highlight format, it's
heavily inspired by [Rust's error messages][].
[Rust's error messages]: https://blog.rust-lang.org/images/2016-08-09-Errors/new_errors.png
For maximal backwards-compatibility, this doesn't change the
formatting of any single-span highlights and it uses extension methods
rather than adding new methods to existing classes.
=> Add support for highlighting multiple spans at once

CHANGELOG.md, lib/src/file.dart, lib/src/span.dart, pubspec.yaml, test/file_test.dart, test/span_test.dart
This is useful when a span may cover multiple logical tokens, and a
user wants to single out a single specific token.
=> Add SourceSpan.subspan()

lib/src/highlighter.dart
Flow analysis currently has a bug preventing for-each loop variables
from being properly promoted in the presence of closures
(https://github.com/dart-lang/sdk/issues/43136); as a result of this
bug the source_span package had two non-null assertions that ought to
have been unnecessary.
I'm preparing a fix for that bug, however if I land it as is, it will
cause the front end to emit errors saying "Operand of null-aware
operation '!' has type '_Highlight' which excludes null"; this in turn
will cause SDK bot breakages (since source_span is imported into the
SDK repo).
So, in order to land the fix, we need to first update the source_span
package to work around the bug; this change does that by allocating a
temporary variable (which *is* promoted correctly).
Once the fix for …
=> Work around flow analysis bug

.travis.yml, CHANGELOG.md, lib/src/highlighter.dart, pubspec.yaml
Reverts https://github.com/dart-lang/source_span/pull/59 and removes now unnecessary `!`s.
This requires a newer sdk than is available on dev, so run tests on be/raw/latest for now.
The dart version in flutter should already be compatible with this version.
=> Reverts https://github.com/dart-lang/source_span/pull/59, remove unnecessary `!`

.travis.yml, CHANGELOG.md, lib/src/highlighter.dart, pubspec.yaml
The 2.10 stable sdk it turns out will not have the sdk fix.
=> Revert the revert of the flow analysis workaround 

CHANGELOG.md, pubspec.yaml
See https://github.com/flutter/flutter/issues/66287, this version works with old/new dart sdks
=> prep to release to unblock flutter

CHANGELOG.md, lib/src/highlighter.dart, pubspec.yaml
Now that https://github.com/dart-lang/sdk/issues/43136 is fixed, the
workaround is no longer needed.
=> Remove workaround for SDK bug.

CHANGELOG.md, pubspec.yaml
Not safe to publish until https://dart-review.googlesource.com/c/sdk/+/168983 works its way internally
- also removes git deps in favor of real deps
=> allow the 2.12 prerelease sdks and prep to publish

CHANGELOG.md, lib/src/charcode.dart, lib/src/highlighter.dart, lib/src/span.dart, pubspec.yaml
Copy in the charcode constants that are used in this package to a
private library.
=> Remove dependency on package:charcode

CHANGELOG.md, lib/src/highlighter.dart, lib/src/utils.dart, pubspec.yaml, test/multiple_highlight_test.dart
If a multiple span highlight was created where all the secondary spans
had `null` URLs they were filtered out from the comparison checking
whether multiple files are involved.
This bug was caused during the null safety migration. A similar bug
previously existed if the primary span had a null URL and is also fixed.
- Take a nullable list in `isAllTheSame`. Avoid using `null` as a
sentinel for no item seen, use `.first` and `.skip(1)` to compare all
elements.
- Add tests for the case of primary and secondary spans with a null URL.
=> Fix header for multispan with null secondary urls

CHANGELOG.md, README.md, example/main.dart, pubspec.yaml
- add an api usage example
- fix an `http` reference in the changelog
=> add an api usage example

CHANGELOG.md, lib/src/file.dart, pubspec.yaml
This makes it possible to efficiently reparse information from around
a `FileSpan`, such as to expand it through surrounding whitespace
characters. Otherwise, a caller would have to call `getText()` which
can be very expensive in a tight loop.
=> Add public access to a SourceFile's code units
